# Generated by Django 4.0.3 on 2023-07-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
